using System;

namespace SoaApp.Dtos
{
    public class BapiOpenItemDto
    {
        public string COMP_CODE { get; set; }
        public string CUSTOMER { get; set; }
        public string SP_GL_IND { get; set; }
        public string CLEAR_DATE { get; set; }
        public string CLR_DOC_NO { get; set; }
        public string ALLOC_NMBR { get; set; }
        public string FISC_YEAR { get; set; }
        public string DOC_NO { get; set; }
        public string ITEM_NUM { get; set; }
        public DateTime PSTNG_DATE { get; set; }
        public DateTime DOC_DATE { get; set; }
        public DateTime ENTRY_DATE { get; set; }
        public string CURRENCY { get; set; }
        public string LOC_CURRCY { get; set; }
        public string REF_DOC_NO { get; set; }
        public string DOC_TYPE { get; set; }
        public string FIS_PERIOD { get; set; }
        public string POST_KEY { get; set; }
        public string DB_CR_IND { get; set; }
        public string BUS_AREA { get; set; }
        public string TAX_CODE { get; set; }
        public decimal LC_AMOUNT { get; set; }
        public decimal AMT_DOCCUR { get; set; }
        public string LC_TAX { get; set; }
        public string TX_DOC_CUR { get; set; }
        public string ITEM_TEXT { get; set; }
        public string BRANCH { get; set; }
        public string BLINE_DATE { get; set; }
        public string PMNTTRMS { get; set; }
        public string DSCT_DAYS1 { get; set; }
        public string DSCT_DAYS2 { get; set; }
        public string NETTERMS { get; set; }
        public string DSCT_PCT1 { get; set; }
        public string DSCT_PCT2 { get; set; }
        public string DISC_BASE { get; set; }
        public string DSC_AMT_LC { get; set; }
        public string DSC_AMT_DC { get; set; }
        public string PYMT_METH { get; set; }
        public string PMNT_BLOCK { get; set; }
        public string FIXEDTERMS { get; set; }
        public string INV_REF { get; set; }
        public string INV_YEAR { get; set; }
        public string INV_ITEM { get; set; }
        public string DUNN_BLOCK { get; set; }
        public string DUNN_KEY { get; set; }
        public string LAST_DUNN { get; set; }
        public string DUNN_LEVEL { get; set; }
        public string DUNN_AREA { get; set; }
        public string DOC_STATUS { get; set; }
        public string NXT_DOCTYP { get; set; }
        public string VAT_REG_NO { get; set; }
        public string REASON_CDE { get; set; }
        public string PMTMTHSUPL { get; set; }
        public string REF_KEY_1 { get; set; }
        public string REF_KEY_2 { get; set; }
        public string T_CURRENCY { get; set; }
        public decimal AMOUNT { get; set; }
        public string NET_AMOUNT { get; set; }
        public string NAME { get; set; }
        public string NAME_2 { get; set; }
        public string NAME_3 { get; set; }
        public string NAME_4 { get; set; }
        public string POSTL_CODE { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public string STREET { get; set; }
        public string PO_BOX { get; set; }
        public string POBX_PCD { get; set; }
        public string POBK_CURAC { get; set; }
        public string BANK_ACCT { get; set; }
        public string BANK_KEY { get; set; }
        public string BANK_CTRY { get; set; }
        public string TAX_NO_1 { get; set; }
        public string TAX_NO_2 { get; set; }
        public string TAX { get; set; }
        public string EQUAL_TAX { get; set; }
        public string REGION { get; set; }
        public string CTRL_KEY { get; set; }
        public string INSTR_KEY { get; set; }
        public string PAYEE_CODE { get; set; }
        public string LANGU { get; set; }
        public string BILL_LIFE { get; set; }
        public string BE_TAXCODE { get; set; }
        public string BILLTAX_LC { get; set; }
        public string BILLTAX_FC { get; set; }
        public string LC_COL_CHG { get; set; }
        public string COLL_CHARG { get; set; }
        public string CHGS_TX_CD { get; set; }
        public string ISSUE_DATE { get; set; }
        public string USAGEDATE { get; set; }
        public string BILL_USAGE { get; set; }
        public string DOMICILE { get; set; }
        public string DRAWER { get; set; }
        public string CTRBNK_LOC { get; set; }
        public string DRAW_CITY1 { get; set; }
        public string DRAWEE { get; set; }
        public string DRAW_CITY2 { get; set; }
        public string DISCT_DAYS { get; set; }
        public string DISCT_RATE { get; set; }
        public string ACCEPTED { get; set; }
        public string BILLSTATUS { get; set; }
        public string PRTEST_IND { get; set; }
        public string BE_DEMAND { get; set; }
        public string OBJ_TYPE { get; set; }
        public string REF_DOC { get; set; }
        public string REF_ORG_UN { get; set; }
        public string REVERSAL_DOC { get; set; }
        public string SP_GL_TYPE { get; set; }
        public string NEG_POSTNG { get; set; }
        public string REF_DOC_NO_LONG { get; set; }
        public string BILL_DOC { get; set; }
    }
}