using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace SoaApp.Migrations
{
    public partial class AddBsidNewTableToDb : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "BSIDNews",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    BUKRS = table.Column<int>(nullable: false),
                    KUNNR = table.Column<int>(nullable: false),
                    UMSKS = table.Column<string>(nullable: true),
                    UMSKZ = table.Column<string>(nullable: true),
                    AUGDT = table.Column<string>(nullable: true),
                    AUGBL = table.Column<string>(nullable: true),
                    ZUONR = table.Column<string>(nullable: true),
                    GJAHR = table.Column<int>(nullable: false),
                    BELNR = table.Column<int>(nullable: false),
                    BUZEI = table.Column<string>(nullable: true),
                    BUDAT = table.Column<DateTime>(nullable: false),
                    BLDAT = table.Column<DateTime>(nullable: false),
                    CPUDT = table.Column<string>(nullable: true),
                    WAERS = table.Column<string>(nullable: true),
                    XBLNR = table.Column<string>(nullable: true),
                    BLART = table.Column<string>(nullable: true),
                    MONAT = table.Column<int>(nullable: false),
                    BSCHL = table.Column<int>(nullable: false),
                    ZUMSK = table.Column<string>(nullable: true),
                    SHKZG = table.Column<string>(nullable: true),
                    GSBER = table.Column<string>(nullable: true),
                    MWSKZ = table.Column<string>(nullable: true),
                    DMBTR = table.Column<double>(nullable: false),
                    WRBTR = table.Column<double>(nullable: false),
                    MWSTS = table.Column<string>(nullable: true),
                    WMWST = table.Column<string>(nullable: true),
                    BDIFF = table.Column<string>(nullable: true),
                    BDIF2 = table.Column<string>(nullable: true),
                    SGTXT = table.Column<string>(nullable: true),
                    PROJN = table.Column<string>(nullable: true),
                    AUFNR = table.Column<string>(nullable: true),
                    ANLN1 = table.Column<string>(nullable: true),
                    ANLN2 = table.Column<string>(nullable: true),
                    SAKNR = table.Column<int>(nullable: false),
                    HKONT = table.Column<int>(nullable: false),
                    FKONT = table.Column<string>(nullable: true),
                    FILKD = table.Column<string>(nullable: true),
                    ZFBDT = table.Column<DateTime>(nullable: false),
                    ZTERM = table.Column<string>(nullable: true),
                    ZBD1T = table.Column<string>(nullable: true),
                    ZBD2T = table.Column<string>(nullable: true),
                    ZBD3T = table.Column<string>(nullable: true),
                    ZBD1P = table.Column<string>(nullable: true),
                    ZBD2P = table.Column<string>(nullable: true),
                    SKFBT = table.Column<string>(nullable: true),
                    SKNTO = table.Column<string>(nullable: true),
                    WSKTO = table.Column<string>(nullable: true),
                    ZLSCH = table.Column<string>(nullable: true),
                    ZLSPR = table.Column<string>(nullable: true),
                    ZBFIX = table.Column<string>(nullable: true),
                    HBKID = table.Column<string>(nullable: true),
                    BVTYP = table.Column<string>(nullable: true),
                    REBZG = table.Column<string>(nullable: true),
                    REBZJ = table.Column<string>(nullable: true),
                    REBZZ = table.Column<string>(nullable: true),
                    SAMNR = table.Column<string>(nullable: true),
                    ANFBN = table.Column<string>(nullable: true),
                    ANFBJ = table.Column<string>(nullable: true),
                    ANFBU = table.Column<string>(nullable: true),
                    ANFAE = table.Column<string>(nullable: true),
                    MANSP = table.Column<string>(nullable: true),
                    MSCHL = table.Column<string>(nullable: true),
                    MADAT = table.Column<string>(nullable: true),
                    MANST = table.Column<string>(nullable: true),
                    MABER = table.Column<string>(nullable: true),
                    XNETB = table.Column<string>(nullable: true),
                    XANET = table.Column<string>(nullable: true),
                    XCPDD = table.Column<string>(nullable: true),
                    XINVE = table.Column<string>(nullable: true),
                    XZAHL = table.Column<string>(nullable: true),
                    MWSK1 = table.Column<string>(nullable: true),
                    DMBT1 = table.Column<string>(nullable: true),
                    WRBT1 = table.Column<string>(nullable: true),
                    MWSK2 = table.Column<string>(nullable: true),
                    DMBT2 = table.Column<string>(nullable: true),
                    WRBT2 = table.Column<string>(nullable: true),
                    MWSK3 = table.Column<string>(nullable: true),
                    DMBT3 = table.Column<string>(nullable: true),
                    WRBT3 = table.Column<string>(nullable: true),
                    BSTAT = table.Column<string>(nullable: true),
                    VBUND = table.Column<string>(nullable: true),
                    VBELN = table.Column<string>(nullable: true),
                    REBZT = table.Column<string>(nullable: true),
                    INFAE = table.Column<string>(nullable: true),
                    STCEG = table.Column<string>(nullable: true),
                    EGBLD = table.Column<string>(nullable: true),
                    EGLLD = table.Column<string>(nullable: true),
                    RSTGR = table.Column<string>(nullable: true),
                    XNOZA = table.Column<string>(nullable: true),
                    VERTT = table.Column<string>(nullable: true),
                    VERTN = table.Column<string>(nullable: true),
                    VBEWA = table.Column<string>(nullable: true),
                    WVERW = table.Column<string>(nullable: true),
                    PROJK = table.Column<string>(nullable: true),
                    FIPOS = table.Column<string>(nullable: true),
                    NPLNR = table.Column<string>(nullable: true),
                    AUFPL = table.Column<string>(nullable: true),
                    APLZL = table.Column<string>(nullable: true),
                    XEGDR = table.Column<string>(nullable: true),
                    DMBE2 = table.Column<string>(nullable: true),
                    DMBE3 = table.Column<string>(nullable: true),
                    DMB21 = table.Column<string>(nullable: true),
                    DMB22 = table.Column<string>(nullable: true),
                    DMB23 = table.Column<string>(nullable: true),
                    DMB31 = table.Column<string>(nullable: true),
                    DMB32 = table.Column<string>(nullable: true),
                    DMB33 = table.Column<string>(nullable: true),
                    BDIF3 = table.Column<string>(nullable: true),
                    XRAGL = table.Column<string>(nullable: true),
                    UZAWE = table.Column<string>(nullable: true),
                    XSTOV = table.Column<string>(nullable: true),
                    MWST2 = table.Column<string>(nullable: true),
                    MWST3 = table.Column<string>(nullable: true),
                    SKNT2 = table.Column<string>(nullable: true),
                    SKNT3 = table.Column<string>(nullable: true),
                    XREF1 = table.Column<string>(nullable: true),
                    XREF2 = table.Column<string>(nullable: true),
                    XARCH = table.Column<string>(nullable: true),
                    PSWSL = table.Column<string>(nullable: true),
                    PSWBT = table.Column<string>(nullable: true),
                    LZBKZ = table.Column<string>(nullable: true),
                    LANDL = table.Column<string>(nullable: true),
                    IMKEY = table.Column<string>(nullable: true),
                    VBEL2 = table.Column<string>(nullable: true),
                    VPOS2 = table.Column<string>(nullable: true),
                    POSN2 = table.Column<string>(nullable: true),
                    ETEN2 = table.Column<string>(nullable: true),
                    FISTL = table.Column<string>(nullable: true),
                    GEBER = table.Column<string>(nullable: true),
                    DABRZ = table.Column<string>(nullable: true),
                    XNEGP = table.Column<string>(nullable: true),
                    KOSTL = table.Column<string>(nullable: true),
                    RFZEI = table.Column<string>(nullable: true),
                    KKBER = table.Column<string>(nullable: true),
                    EMPFB = table.Column<string>(nullable: true),
                    PRCTR = table.Column<string>(nullable: true),
                    XREF3 = table.Column<string>(nullable: true),
                    QSSKZ = table.Column<string>(nullable: true),
                    ZINKZ = table.Column<string>(nullable: true),
                    DTWS1 = table.Column<string>(nullable: true),
                    DTWS2 = table.Column<string>(nullable: true),
                    DTWS3 = table.Column<string>(nullable: true),
                    DTWS4 = table.Column<string>(nullable: true),
                    XPYPR = table.Column<string>(nullable: true),
                    KIDNO = table.Column<string>(nullable: true),
                    ABSBT = table.Column<string>(nullable: true),
                    CCBTC = table.Column<string>(nullable: true),
                    PYCUR = table.Column<string>(nullable: true),
                    PYAMT = table.Column<string>(nullable: true),
                    BUPLA = table.Column<string>(nullable: true),
                    SECCO = table.Column<string>(nullable: true),
                    CESSION_KZ = table.Column<string>(nullable: true),
                    PPDIFF = table.Column<string>(nullable: true),
                    PPDIF2 = table.Column<string>(nullable: true),
                    PPDIF3 = table.Column<string>(nullable: true),
                    KBLNR = table.Column<string>(nullable: true),
                    KBLPOS = table.Column<string>(nullable: true),
                    GRANT_NBR = table.Column<string>(nullable: true),
                    GMVKZ = table.Column<string>(nullable: true),
                    SRTYPE = table.Column<string>(nullable: true),
                    LOTKZ = table.Column<string>(nullable: true),
                    FKBER = table.Column<string>(nullable: true),
                    INTRENO = table.Column<string>(nullable: true),
                    PPRCT = table.Column<string>(nullable: true),
                    BUZID = table.Column<string>(nullable: true),
                    AUGGJ = table.Column<string>(nullable: true),
                    HKTID = table.Column<string>(nullable: true),
                    BUDGET_PD = table.Column<string>(nullable: true),
                    PAYS_PROV = table.Column<string>(nullable: true),
                    PAYS_TRAN = table.Column<string>(nullable: true),
                    MNDID = table.Column<string>(nullable: true),
                    KONTT = table.Column<string>(nullable: true),
                    KONTL = table.Column<string>(nullable: true),
                    UEBGDAT = table.Column<string>(nullable: true),
                    VNAME = table.Column<string>(nullable: true),
                    EGRUP = table.Column<string>(nullable: true),
                    BTYPE = table.Column<string>(nullable: true),
                    OIEXGNUM = table.Column<string>(nullable: true),
                    OINETCYC = table.Column<string>(nullable: true),
                    OIEXGTYP = table.Column<string>(nullable: true),
                    PROPMANO = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BSIDNews", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "BSIDNews");
        }
    }
}
