using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace SoaApp.Migrations
{
    public partial class AddRBkpfNewTableToDb : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "R_BKPFNews",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    BUKRS = table.Column<int>(nullable: false),
                    BELNR = table.Column<int>(nullable: false),
                    GJAHR = table.Column<int>(nullable: false),
                    BLART = table.Column<string>(nullable: true),
                    BLDAT = table.Column<DateTime>(nullable: false),
                    BUDAT = table.Column<DateTime>(nullable: false),
                    MONAT = table.Column<int>(nullable: false),
                    CPUDT = table.Column<string>(nullable: true),
                    CPUTM = table.Column<string>(nullable: true),
                    AEDAT = table.Column<string>(nullable: true),
                    UPDDT = table.Column<string>(nullable: true),
                    WWERT = table.Column<string>(nullable: true),
                    USNAM = table.Column<string>(nullable: true),
                    TCODE = table.Column<string>(nullable: true),
                    BVORG = table.Column<string>(nullable: true),
                    XBLNR = table.Column<string>(nullable: true),
                    DBBLG = table.Column<string>(nullable: true),
                    STBLG = table.Column<string>(nullable: true),
                    STJAH = table.Column<string>(nullable: true),
                    BKTXT = table.Column<string>(nullable: true),
                    WAERS = table.Column<string>(nullable: true),
                    KURSF = table.Column<string>(nullable: true),
                    KZWRS = table.Column<string>(nullable: true),
                    KZKRS = table.Column<string>(nullable: true),
                    BSTAT = table.Column<string>(nullable: true),
                    XNETB = table.Column<string>(nullable: true),
                    FRATH = table.Column<string>(nullable: true),
                    XRUEB = table.Column<string>(nullable: true),
                    GLVOR = table.Column<string>(nullable: true),
                    GRPID = table.Column<string>(nullable: true),
                    DOKID = table.Column<string>(nullable: true),
                    ARCID = table.Column<string>(nullable: true),
                    IBLAR = table.Column<string>(nullable: true),
                    AWTYP = table.Column<string>(nullable: true),
                    AWKEY = table.Column<string>(nullable: true),
                    FIKRS = table.Column<string>(nullable: true),
                    HWAER = table.Column<string>(nullable: true),
                    HWAE2 = table.Column<string>(nullable: true),
                    HWAE3 = table.Column<string>(nullable: true),
                    KURS2 = table.Column<string>(nullable: true),
                    KURS3 = table.Column<string>(nullable: true),
                    BASW2 = table.Column<string>(nullable: true),
                    BASW3 = table.Column<string>(nullable: true),
                    UMRD2 = table.Column<string>(nullable: true),
                    UMRD3 = table.Column<string>(nullable: true),
                    XSTOV = table.Column<string>(nullable: true),
                    STODT = table.Column<string>(nullable: true),
                    XMWST = table.Column<string>(nullable: true),
                    CURT2 = table.Column<string>(nullable: true),
                    CURT3 = table.Column<string>(nullable: true),
                    KUTY2 = table.Column<string>(nullable: true),
                    KUTY3 = table.Column<string>(nullable: true),
                    XSNET = table.Column<string>(nullable: true),
                    AUSBK = table.Column<string>(nullable: true),
                    XUSVR = table.Column<string>(nullable: true),
                    DUEFL = table.Column<string>(nullable: true),
                    AWSYS = table.Column<string>(nullable: true),
                    TXKRS = table.Column<string>(nullable: true),
                    CTXKRS = table.Column<string>(nullable: true),
                    LOTKZ = table.Column<string>(nullable: true),
                    XWVOF = table.Column<string>(nullable: true),
                    STGRD = table.Column<string>(nullable: true),
                    PPNAM = table.Column<string>(nullable: true),
                    PPDAT = table.Column<string>(nullable: true),
                    PPTME = table.Column<string>(nullable: true),
                    PPTCOD = table.Column<string>(nullable: true),
                    BRNCH = table.Column<string>(nullable: true),
                    NUMPG = table.Column<string>(nullable: true),
                    ADISC = table.Column<string>(nullable: true),
                    XREF1_HD = table.Column<string>(nullable: true),
                    XREF2_HD = table.Column<string>(nullable: true),
                    XREVERSAL = table.Column<string>(nullable: true),
                    REINDAT = table.Column<string>(nullable: true),
                    RLDNR = table.Column<string>(nullable: true),
                    LDGRP = table.Column<string>(nullable: true),
                    PROPMANO = table.Column<string>(nullable: true),
                    XBLNR_ALT = table.Column<string>(nullable: true),
                    VATDATE = table.Column<string>(nullable: true),
                    DOCCAT = table.Column<string>(nullable: true),
                    XSPLIT = table.Column<string>(nullable: true),
                    CASH_ALLOC = table.Column<string>(nullable: true),
                    FOLLOW_ON = table.Column<string>(nullable: true),
                    XREORG = table.Column<string>(nullable: true),
                    SUBSET = table.Column<string>(nullable: true),
                    KURST = table.Column<string>(nullable: true),
                    KURSX = table.Column<string>(nullable: true),
                    KUR2X = table.Column<string>(nullable: true),
                    KUR3X = table.Column<string>(nullable: true),
                    XMCA = table.Column<string>(nullable: true),
                    RESUBMISSION = table.Column<string>(nullable: true),
                    SAPF15_STATUS = table.Column<string>(nullable: true),
                    PSOTY = table.Column<string>(nullable: true),
                    PSOAK = table.Column<string>(nullable: true),
                    PSOKS = table.Column<string>(nullable: true),
                    PSOSG = table.Column<string>(nullable: true),
                    PSOFN = table.Column<string>(nullable: true),
                    INTFORM = table.Column<string>(nullable: true),
                    INTDATE = table.Column<string>(nullable: true),
                    PSOBT = table.Column<string>(nullable: true),
                    PSOZL = table.Column<string>(nullable: true),
                    PSODT = table.Column<string>(nullable: true),
                    PSOTM = table.Column<string>(nullable: true),
                    FM_UMART = table.Column<string>(nullable: true),
                    CCINS = table.Column<string>(nullable: true),
                    CCNUM = table.Column<string>(nullable: true),
                    SSBLK = table.Column<string>(nullable: true),
                    BATCH = table.Column<string>(nullable: true),
                    SNAME = table.Column<string>(nullable: true),
                    SAMPLED = table.Column<string>(nullable: true),
                    EXCLUDE_FLAG = table.Column<string>(nullable: true),
                    BLIND = table.Column<string>(nullable: true),
                    OFFSET_STATUS = table.Column<string>(nullable: true),
                    OFFSET_REFER_DAT = table.Column<string>(nullable: true),
                    PENRC = table.Column<string>(nullable: true),
                    KNUMV = table.Column<string>(nullable: true),
                    OINETNUM = table.Column<string>(nullable: true),
                    OINJAHR = table.Column<string>(nullable: true),
                    OININD = table.Column<string>(nullable: true),
                    RECHN = table.Column<string>(nullable: true),
                    PYBASTYP = table.Column<string>(nullable: true),
                    PYBASNO = table.Column<string>(nullable: true),
                    PYBASDAT = table.Column<string>(nullable: true),
                    PYIBAN = table.Column<string>(nullable: true),
                    INWARDNO_HD = table.Column<string>(nullable: true),
                    INWARDDT_HD = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_R_BKPFNews", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "R_BKPFNews");
        }
    }
}
