using System.ComponentModel.DataAnnotations;

namespace SoaApp.Models
{
    public class BKPF
    {
        [Key]
        public int Id { get; set; }
        public string BUKRS { get; set; }
        public string BELNR { get; set; }
        public string GJAHR { get; set; }
        public string BLART { get; set; }
        public string BLDAT { get; set; }
        public string BUDAT { get; set; }
        public string MONAT { get; set; }
        public string CPUDT { get; set; }
        public string CPUTM { get; set; }
        public string AEDAT { get; set; }
        public string UPDDT { get; set; }
        public string WWERT { get; set; }
        public string USNAM { get; set; }
        public string TCODE { get; set; }
        public string BVORG { get; set; }
        public string XBLNR { get; set; }
        public string DBBLG { get; set; }
        public string STBLG { get; set; }
        public string STJAH { get; set; }
        public string BKTXT { get; set; }
        public string WAERS { get; set; }
        public string KURSF { get; set; }
        public string KZWRS { get; set; }
        public string KZKRS { get; set; }
        public string BSTAT { get; set; }
        public string XNETB { get; set; }
        public string FRATH { get; set; }
        public string XRUEB { get; set; }
        public string GLVOR { get; set; }
        public string GRPID { get; set; }
        public string DOKID { get; set; }
        public string ARCID { get; set; }
        public string IBLAR { get; set; }
        public string AWTYP { get; set; }
        public string AWKEY { get; set; }
        public string FIKRS { get; set; }
        public string HWAER { get; set; }
        public string HWAE2 { get; set; }
        public string HWAE3 { get; set; }
        public string KURS2 { get; set; }
        public string KURS3 { get; set; }
        public string BASW2 { get; set; }
        public string BASW3 { get; set; }
        public string UMRD2 { get; set; }
        public string UMRD3 { get; set; }
        public string XSTOV { get; set; }
        public string STODT { get; set; }
        public string XMWST { get; set; }
        public string CURT2 { get; set; }
        public string CURT3 { get; set; }
        public string KUTY2 { get; set; }
        public string KUTY3 { get; set; }
        public string XSNET { get; set; }
        public string AUSBK { get; set; }
        public string XUSVR { get; set; }
        public string DUEFL { get; set; }
        public string AWSYS { get; set; }
        public string TXKRS { get; set; }
        public string CTXKRS { get; set; }
        public string LOTKZ { get; set; }
        public string XWVOF { get; set; }
        public string STGRD { get; set; }
        public string PPNAM { get; set; }
        public string PPDAT { get; set; }
        public string PPTME { get; set; }
        public string PPTCOD { get; set; }
        public string BRNCH { get; set; }
        public string NUMPG { get; set; }
        public string ADISC { get; set; }
        public string XREF1_HD { get; set; }
        public string XREF2_HD { get; set; }
        public string XREVERSAL { get; set; }
        public string REINDAT { get; set; }
        public string RLDNR { get; set; }
        public string LDGRP { get; set; }
        public string PROPMANO { get; set; }
        public string XBLNR_ALT { get; set; }
        public string VATDATE { get; set; }
        public string DOCCAT { get; set; }
        public string XSPLIT { get; set; }
        public string CASH_ALLOC { get; set; }
        public string FOLLOW_ON { get; set; }
        public string XREORG { get; set; }
        public string SUBSET { get; set; }
        public string KURST { get; set; }
        public string KURSX { get; set; }
        public string KUR2X { get; set; }
        public string KUR3X { get; set; }
        public string XMCA { get; set; }
        public string RESUBMISSION { get; set; }
        public string SAPF15_STATUS { get; set; }
        public string PSOTY { get; set; }
        public string PSOAK { get; set; }
        public string PSOKS { get; set; }
        public string PSOSG { get; set; }
        public string PSOFN { get; set; }
        public string INTFORM { get; set; }
        public string INTDATE { get; set; }
        public string PSOBT { get; set; }
        public string PSOZL { get; set; }
        public string PSODT { get; set; }
        public string PSOTM { get; set; }
        public string FM_UMART { get; set; }
        public string CCINS { get; set; }
        public string CCNUM { get; set; }
        public string SSBLK { get; set; }
        public string BATCH { get; set; }
        public string SNAME { get; set; }
        public string SAMPLED { get; set; }
        public string EXCLUDE_FLAG { get; set; }
        public string BLIND { get; set; }
        public string OFFSET_STATUS { get; set; }
        public string OFFSET_REFER_DAT { get; set; }
        public string PENRC { get; set; }
        public string KNUMV { get; set; }
        public string OINETNUM { get; set; }
        public string OINJAHR { get; set; }
        public string OININD { get; set; }
        public string RECHN { get; set; }
        public string PYBASTYP { get; set; }
        public string PYBASNO { get; set; }
        public string PYBASDAT { get; set; }
        public string PYIBAN { get; set; }
        public string INWARDNO_HD { get; set; }
        public string INWARDDT_HD { get; set; }
    }
}